name: Modify File at Intervals

on:
    schedule:
  - cron: '*/1 * * * *'  # This cron expression runs the workflow every minute (initially)
  - cron: '*/5 * * * *'  # Runs every 5 minutes (after 1 minute)
  - cron: '0,30 * * * *'  # Runs every 30 minutes (after 5 minutes)

    jobs:
      modify-file:
        runs-on: ubuntu-latest  # Run on the latest Ubuntu environment          
steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # This checks out your repository so you can modify the file

      - name: Modify the file with timestamp
        run: |
         echo "Modified at $(date)" >> myfile.txt  # Append current date and time to myfile.txt
      - name: Commit and push changes

        run: |

          git config --global user.name "GitHub Actions"
                                                                                                                              git config --global user.email "actions@github.com"
                                                                                                                                        git add myfile.txt
                                                                                                                                                  git commit -m "Modified myfile.txt at $(date)"
                                                                                                                                                            git push
                                                                                                                                                            
